### ISSUE TITLE
update return_fields method to return title and text description of variables

### ISSUE THREAD

**Issue by SubratoChakravorty** [SubratoChakravorty/ECE-229-Group5-final-project#3]
@danielyou0230 Can you work on that? Update the return_fields function inside the univariate_methods, I currently have a hardcoded dictionary which has variable name mapped to short description. Can you do something like having the variable name mapped to a short title and descriptionp as some of the descriptions are too long to be used in the dropdown. For example,
{'N1GROUP': {'title' : 'Group Work', 'desp': 'Science teacher has students work in small groups'}}.

You can save this as a json file and load it when someone calls the method if you want.

**Comment by SubratoChakravorty** [comment]
Also separate the output into categorical and continuous variables.

**Comment by danielyou0230** [comment]
a50e4e22cdb24e9e492dd472bc617de11af92050 added. I added usage in the docstring, so you can run it to see if it fits you need.

But what do you mean by separating into categorical and continuous variables? Two separate *.json files

```
categorical.json
continuous.json
```

or within same file but with top level being categorical and continuous like

```
{
  "categorical": {
    ...
  }
  "continuous": {
    ...
  }
}
```

After all I think it should be fine because this function is just returning the title and description of the associated variable.

**Comment by SubratoChakravorty** [comment]
Frontend also needs to know whether each variable is categorical or continuous. As some dropdowns will only show categorical variables. We have to decide what will be the best way to do it. For now, you can implement your second approach, 
```
{
  "categorical": {
    ...
  }
  "continuous": {
    ...
  }
}
```
@Ian-Mint is better placed to answer what will be a suitable format for him.

**Comment by Ian-Mint** [comment]
The implementation you suggest looks good to me.

**Comment by SubratoChakravorty** [comment]
@Ian-Mint I implemented that group means and count method only to see that you already implemented that in your code.
