### ISSUE TITLE
get_var_info 

### ISSUE THREAD

**Issue by SubratoChakravorty** [SubratoChakravorty/ECE-229-Group5-final-project#6]
@danielyou0230 current version of the ```get_var_info()``` returns the variable info if you probe it using variable keys. But you can't get all the available fields from the dataset unless you already know the keys. 
@Ian-Mint Do you think, it will be better if it handles the case where if the name is empty, all the variables with their titles and descriptions are returned.

**Comment by danielyou0230** [comment]
I see you point, it's much like using a consistent api. @Ian-Mint could you give me some scenarios, I think it highly depends on how the frontend is implemented.

For instance, for dropdown menu, we might need a subset of variables, say either all categorical or continuous variables, which would be rather simple because they can be predefined in the *.json file. But a more general case requires only a subset of the variables that are grouped based on the actual usage in the frontend, in that case, we might need additional information that contains the groups of the variable with the function below.

```
import json

def get_var_group(group, file="/path/to/default/file"):
  # return a list of variables of certain group
  with open(file, "r") as f:
    content = json.load(f)
  return content[group]
```

the file that defines the group of the variable is also a *.json
```
{
  "group_1": ["var_1", ..., "var_n"],
  "group_2": ["var_1", ..., "var_m"]
  ...
}
```

This way, the implementation of `get_var_info` can remain unchanged while using it along with `get_var_group` and the json file above, and the code for frontend can be reduced.

```
# frontend
def show_some_graph(group):
  vars = get_var_group(group)
  descriptors = get_var_info(vars)
  
  # frontend code here (plot, layout, etc.)
  ...
```

**Comment by Ian-Mint** [comment]
In my implementation I need:

1. A list of all categorical variables
2. A list of all continuous variables

These will be used to populate the dropdown menus. Then, I will have user-input fields that I will look for more information on.

For the implementation passing me one `categorical` dictionary and one `continuous` dictionary would resolve both of these scenarios. A single `DataFrame` like:
```
var           short   long                                type
X1SEX    Sex    The sex of the student    categorical
...             ...        ...                                    ...
```
would also work quite well.

You should pass it all to me at once, I can then use the data structure to get descriptors, which makes the frontend implementation more flexible. You should also handle the path to the data file so the frontend doesn't have to.

**Comment by danielyou0230** [comment]
@Ian-Mint just commit on another branch according to your requirements. I've export the `pandas.DataFrame` you asked for to `data/variables.csv` ([here](https://github.com/SubratoChakravorty/ECE-229-Group5-final-project/blob/backend-var/data/variables.csv)), make sure to check it and let me know if the type is wrong.

Note that `src.univariate_methods.get_var_info` is now changed to just return the DataFrame you need. The file path would be resolved later.

**Comment by Ian-Mint** [comment]
looks good! thanks.

**Comment by SubratoChakravorty** [comment]
Great! Daniel close the issue when you are done.
